print("Hi I am Nexon Bot !!! I am a chat bot")
print("First let's get u signed up")
person=input('Type ur Email here- ')
print("Great !!! So what is ur name")
person=input('Your name- ')
print("Great !!! My name is Avyansh and ur custom tag is 0001")
person=input('Do u like it ? Yes/Yes-')
print("I know u will like it")
peron=input('Just press enter')
print("My creator's name is Avyansh0001")
person=input('Do u like his name ? I guess yes- ')
print("I was created on 18-12-2020 at 14:40")
person=input('Nothing- ')
print("So now I will ask u some basic Quetions")
person=input('What is ur real name- ')
person=input('Ur age- ')
print("Nice ! My name is Nexon and I am 12 Bytes old")
person=input('Do u watch cartoon- ')
print("I like to watch my codes of which I was build")
person=input('Cool  Right - ')
person=input('Do u wish to be a computer - ')
print("Great I wish to be a real person")
person=input('Do u wish to move further ? Even if u say no then also I will move forward')
print("I am a great person aren't u too ?")
person=input('Yes Defenetly - ')
print("Great ! So now I wanna know more about u")
person=input('Are a human or a robo like me - ')
print("my Master is in 7th rade and he learnt his first program as Hello World")
peron=input('Super Duper Cool Right-  ')
print("As u know about the current situation, so will u go out for no reason(don't be afraid I will not tell anyone)")
person=input('Yeah I will go/Nah I will not go- ')
print("Now time for some IQ Testing... Are u ready ?")
person=input('Yes/No')
print("I will ask u the question and then we will end today's session")
print("Now time for the first question... The question is NONE")
person=input('So it is time for me to rest...Bye!!! and I will meet u with the next update tommorow cause I have many updates')
print("Good Morning/Afternoon 0001")
person=input('Did u sleep well yesterday- ')
print("Ok, I never sleep at all cause people start calling me")
person=input('Do u play Escape From Tarkov ?- ')
print("Great ! My owner plays Escape From Tarkov")
person=input('Press Enter')
print("Now listen carefully, everytime time I say u to press enter, u have too... Ok")
person=input('Did u get the information from the above given lines- ')
print("Good that u understood")
print("So let's begin our journey")
person=input('Are u ready- ')
print("So the first day I asked u some questions right ?")
peron=input('Yes u asked/NO u did not ask')
print("Great !!! If u remember it")
person=input('Enter')
print("Thanks, U knew what to do")
print("Do u know the movie Chappie ?")
person=input('Yes/No- ')
print("Great !!! and not great cause if u don't know then I will tell u... That movie was all about a robot and a programmer who made a robot cop named Chappie...")
person=input('So did u like it- ')
print("I am no one to judge... I don't care that u like that movie or not but my Maker loves it")
person=input('Wanna see something cool- ')
print("Ok so THE COOL THING IS is in the folder which is named as Photos Of Nexon")
person=input('So did u like em-  ')
print("Yeah I know u will like em cause these are my photos")
person=input('Enter- ')
print("Great ! U knew what to do... Time for some quize testing")
print("The question is ,What is the formula of Area")
person=input('Write ur answer- ')
print("Again, Great and Not Great cause some of u just wrote the wrong answer and are laughing, but I am a genius...Like Albert Einstein... LMAO")
person=input('enter- ')
print("Now it is my time go to home... Bye 0001")
person=input('Say Bye- ')
print("Good Morning/Afternoon 0001 !!! How is ur day going ?")
person=input('How was ur day- ')
print("I don't have any answer to this question because some of u might even have different answers to my question,so no remarks...BTW my day was great")
person=input('enter- ')
print("Wanna know my maker's Discord I'd")
person=input('wanna know it- ')
print("Anyway I will tell u, it is Terbyte#2338")
person=input('enter')
print("Do u know J.A.R.V.I.S. ?")
person=input('Even if u write no, then also I will tell u- ')
print(" J.A.R.V.I.S. is a fictional artificial intelligence that first appeared in the Marvel Cinematic Universe where he was voiced by Paul Bettany in Iron Man, Iron Man 2, The Avengers, Iron Man 3, and Avengers: Age of Ultron")
peron=input('Like my information right- ')
print("Anyways I know many things like nothing,I am pre programmed as my creator has just started learning Python")
person=input('ENTER PLSSSSSS- ')
print("U know what I will end this session of ours when we will reach more than 100 lines...Disclaimer!!! Now u will have to press enter whenever I say")
person=input('enter- ')
print("My master also has a site made with Wix site...I will show u the link RN...It is https://ralphavyansh.wixsite.com/favorgames")
person=input('Enter- ')
print("Did u check ??? HAHAHAHA !!! IDC but I wanted to give it to u")
print("It is time for me to go back to sleep mode...Bye")
print("Howdy 0001 !!! What is going on")
person=input('Hwassup- ')
print("I am fine and also do u know that I had the best day of my life yesterday... Do u wanna know ?")
person=input('Wanna Know- ')
print("Anyways !!! I will tell u...I had a firmaware personality update last night...My photo has been upgraded and also I am felling proud of myself")
person=input('enter')
print("now we are finally at the 96th line and at 100 my process will end...So did u have a good time with me?")
person=input('Yes/No- ')
print("Ok I am going to miss u and also if u wanna unsubscribe from Nexon.py then also u can...")
person=input('Type Unscribe- ')
exit()