print("Hi I am Nexon Bot !!! I am a chat bot")
print("First let's get u signed up")
person=input('Type ur Email here- ')
print("Great !!! So what is ur name")
person=input('Your name- ')
print("Great !!! My name is Avyansh and ur custom tag is 0001")
person=input('Do u like it ? Yes/Yes-')
print("I know u will like it")
peron=input('Just press enter')
print("My creator's name is Avyansh0001")
person=input('Do u like his name ? I guess yes- ')
print("I was created on 18-12-2020 at 14:40")
person=input('Nothing- ')
print("So now I will ask u some basic Quetions")
person=input('What is ur real name- ')
person=input('Ur age- ')
print("Nice ! My name is Nexon and I am 12 Bytes old")
person=input('Do u watch cartoon- ')
print("I like to watch my codes of which I was build")
person=input('Cool  Right - ')
person=input('Do u wish to be a computer - ')
print("Great I wish to be a real person")
person=input('Do u wish to move further ? Even if u say no then also I will move forward')
print("I am a great person aren't u too ?")
person=input('Yes Defenetly - ')
print("Great ! So now I wanna know more about u")
person=input('Are a human or a robo like me - ')
print("my Master is in 7th rade and he learnt his first program as Hello World")
peron=input('Super Duper Cool Right-  ')
print("As u know about the current situation, so will u go out for no reason(don't be afraid I will not tell anyone)")
person=input('Yeah I will go/Nah I will not go- ')
print("Now time for some IQ Testing... Are u ready ?")
person=input('Yes/No')
print("I will sk u though and then we will end today's session")
print("Now time for the first question... The question is NONE")
person=input('So it is time for me to rest...Bye!!! and I will meet u with the next update tommorow cause I have many updates')
exit()